### PR TITLE
use https rather than http for the returned imageUrl

### PR DESCRIPTION
**Pull request by tomgasson**
Even though the metadata URL is called via `https://` from #4, it still returns a `http://` imageURL. Here I'm just find-replacing that url. Could also strip it back to a protocol relative url, but that's now ill-advised (see the update [here](http://www.paulirish.com/2010/the-protocol-relative-url/)).

### CODE REVIEW

**Comment by cedricr** [comment]
@tomgasson alternatively, check my comment on https://github.com/gmaclennan/leaflet-bing-layer/commit/408f43e18ac800eedbbbb3bec4072dd120974f22

**Comment by tomgasson** [comment]
Yep, that's a better way to do it. Code updated to suit

**Comment by ggl** [comment]
You could use location.protocol instead of hardcoding the scheme.

**Comment by jengeb-rbb** [comment]
It would be great if this PR could get integrated into master.

**Comment by gmaclennan** [comment]
@tomgasson thanks for this, so sorry for the delay, I haven't been checking these repos for a while.

**Pull request merged**
